// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGg2ZDI8DYCpOHZUl0axojPJbQe_TkJ_A',
    appId: '1:1070047694833:web:c707e23401e671ee173e50',
    messagingSenderId: '1070047694833',
    projectId: 'autointel-6c14d',
    authDomain: 'autointel-6c14d.firebaseapp.com',
    storageBucket: 'autointel-6c14d.firebasestorage.app',
    measurementId: 'G-873H29GXMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc6lwl_dMbDAiLnZSC-tvpQNG3lAFsFcU',
    appId: '1:1070047694833:android:681d82f551423946173e50',
    messagingSenderId: '1070047694833',
    projectId: 'autointel-6c14d',
    storageBucket: 'autointel-6c14d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHMI3hl749dY5pbhXFg3dS9b9kEY4nyDo',
    appId: '1:1070047694833:ios:5ebb2310c2467acc173e50',
    messagingSenderId: '1070047694833',
    projectId: 'autointel-6c14d',
    storageBucket: 'autointel-6c14d.firebasestorage.app',
    iosBundleId: 'com.autointeldiagnostics.autointel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHMI3hl749dY5pbhXFg3dS9b9kEY4nyDo',
    appId: '1:1070047694833:ios:260b72e71cf50653173e50',
    messagingSenderId: '1070047694833',
    projectId: 'autointel-6c14d',
    storageBucket: 'autointel-6c14d.firebasestorage.app',
    iosBundleId: 'com.example.autoIntel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGg2ZDI8DYCpOHZUl0axojPJbQe_TkJ_A',
    appId: '1:1070047694833:web:aa6320cace6b7c2f173e50',
    messagingSenderId: '1070047694833',
    projectId: 'autointel-6c14d',
    authDomain: 'autointel-6c14d.firebaseapp.com',
    storageBucket: 'autointel-6c14d.firebasestorage.app',
    measurementId: 'G-J9TBLCYKBK',
  );

}